# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"

[package]
disabled=true

[git_branch]
disabled=false

[git_state]
disabled=true

[git_commit]
disabled=true

[git_status]
disabled=true

[aws]
disabled=false

[python]
disabled=true

[nodejs]
disabled=false
detect_extensions=["js", "jsx", "mjs", "cjs", "ts", "tsx"]

[directory]
truncation_length=8
truncate_to_repo=false
use_logical_path=true

[cmd_duration]
min_time=10
